### ISSUE TITLE
Endless data synchronization

### ISSUE THREAD

**Issue by dulko99** [brunyman/MPDB#124]
There is endless data synchronization.
Mysql tables have been created!

Tried different versions of the plugin

I am using MariaDB database

Thermos Server Core 1.7.10
```
`>mpdb importData
[22:31:38 INFO]: [MysqlPlayerDataBridge] Starting import data process!
[22:31:38 INFO]: [MysqlPlayerDataBridge] Processing 2 players...
[22:31:38 INFO]:  Import data progress: 1/2
[22:31:38 WARN]: [MysqlPlayerDataBridge] Task #55 for MysqlPlayerDataBridge v4.1.0 generated an exception
java.lang.NoSuchMethodError: com.mojang.authlib.GameProfile.<init>(Ljava/lang/String;Ljava/lang/String;)V
        at net.craftersland.data.bridge.utils.nms.Version_1_7_R4_Kauldron.loadPlayer(Version_1_7_R4_Kauldron.java:74) ~[?:?]
        at net.craftersland.data.bridge.commands.handlers.ImportCmd$1$1.run(ImportCmd.java:45) ~[?:?]
        at org.bukkit.craftbukkit.v1_7_R4.scheduler.CraftTask.run(CraftTask.java:71) ~[CraftTask.class:1.7.10-1614.58]
        at org.bukkit.craftbukkit.v1_7_R4.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:346) [CraftScheduler.class:1.7.10-1614.58]
        at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:905) [MinecraftServer.class:?]
        at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:432) [lt.class:?]
        at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:841) [MinecraftServer.class:?]
        at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:693) [MinecraftServer.class:?]
        at java.lang.Thread.run(Thread.java:750) [?:1.8.0_392]
[22:31:41 ERROR]: [MysqlPlayerDataBridge] Could not connect to mysql database! Error: Could not create connection to database server. Attempted reconnect 3 times. Giving up.
[22:31:57 WARN]: [MysqlPlayerDataBridge] Database connection failed. Reconnecting...
[22:31:57 INFO]: [MysqlPlayerDataBridge] Connecting to the database...

```
Judging by the log, the GameProfile method cannot be found

**Comment by pavl21** [comment]
same problem
