### ISSUE TITLE
MPDB not being able to successfully convert Items

### ISSUE THREAD

**Issue by Fly1337** [brunyman/MPDB#130]
Hello!
I'm unsure why this error occurs after updating from 1.20.2 to 1.20.6. I know that there are issues with Essentials because there is no proper 1.20.6 Version yet but I think that should normally not affect the plugins conversion.

```
[13:15:42] [Server thread/INFO]: Phoenixfly1337[%censored-ip%] logged in with entity id 469 at ([Citybuild]0.5074508437270664, 65.0, 0.4919227488376793)
[13:15:42] [Server thread/WARN]: java.lang.RuntimeException: Essentials API is called before Essentials is loaded.
[13:15:42] [Server thread/WARN]: 	at EssentialsX-2.21.0-dev+81-cde7184.jar//com.earth2me.essentials.api.Economy.getUserByUUID(Economy.java:109)
[13:15:42] [Server thread/WARN]: 	at EssentialsX-2.21.0-dev+81-cde7184.jar//com.earth2me.essentials.api.Economy.getMoneyExact(Economy.java:160)
[13:15:42] [Server thread/WARN]: 	at EssentialsX-2.21.0-dev+81-cde7184.jar//com.earth2me.essentials.economy.vault.VaultEconomyProvider.getBalance(VaultEconomyProvider.java:116)
[13:15:42] [Server thread/WARN]: 	at MysqlPlayerDataBridge-v4.12.2.jar//net.craftersland.data.bridge.events.handlers.EconomyDataHandler.backupAndResetLocalBalance(EconomyDataHandler.java:488)
[13:15:42] [Server thread/WARN]: 	at MysqlPlayerDataBridge-v4.12.2.jar//net.craftersland.data.bridge.events.handlers.EconomyDataHandler.access$2(EconomyDataHandler.java:486)
[13:15:42] [Server thread/WARN]: 	at MysqlPlayerDataBridge-v4.12.2.jar//net.craftersland.data.bridge.events.handlers.EconomyDataHandler$1.run(EconomyDataHandler.java:119)
[13:15:42] [Server thread/WARN]: 	at org.bukkit.craftbukkit.scheduler.CraftTask.run(CraftTask.java:101)
[13:15:42] [Server thread/WARN]: 	at org.bukkit.craftbukkit.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:482)
[13:15:42] [Server thread/WARN]: 	at net.minecraft.server.MinecraftServer.tickChildren(MinecraftServer.java:1703)
[13:15:42] [Server thread/WARN]: 	at net.minecraft.server.dedicated.DedicatedServer.tickChildren(DedicatedServer.java:468)
[13:15:42] [Server thread/WARN]: 	at net.minecraft.server.MinecraftServer.tickServer(MinecraftServer.java:1575)
[13:15:42] [Server thread/WARN]: 	at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1235)
[13:15:42] [Server thread/WARN]: 	at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:326)
[13:15:42] [Server thread/WARN]: 	at java.base/java.lang.Thread.run(Thread.java:1583)
[13:15:42] [Server thread/WARN]: [MysqlPlayerDataBridge] Task #2478 for MysqlPlayerDataBridge v4.12.2 generated an exception
java.lang.NullPointerException: Cannot invoke "java.lang.Double.doubleValue()" because "<local2>" is null
	at MysqlPlayerDataBridge-v4.12.2.jar/net.craftersland.data.bridge.events.handlers.EconomyDataHandler$1.run(EconomyDataHandler.java:246) ~[MysqlPlayerDataBridge-v4.12.2.jar:?]
	at org.bukkit.craftbukkit.scheduler.CraftTask.run(CraftTask.java:101) ~[paper-1.20.6.jar:git-Paper-62]
	at org.bukkit.craftbukkit.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:482) ~[paper-1.20.6.jar:git-Paper-62]
	at net.minecraft.server.MinecraftServer.tickChildren(MinecraftServer.java:1703) ~[paper-1.20.6.jar:git-Paper-62]
	at net.minecraft.server.dedicated.DedicatedServer.tickChildren(DedicatedServer.java:468) ~[paper-1.20.6.jar:git-Paper-62]
	at net.minecraft.server.MinecraftServer.tickServer(MinecraftServer.java:1575) ~[paper-1.20.6.jar:git-Paper-62]
	at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1235) ~[paper-1.20.6.jar:git-Paper-62]
	at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:326) ~[paper-1.20.6.jar:git-Paper-62]
	at java.base/java.lang.Thread.run(Thread.java:1583) ~[?:?]
[13:15:55] [Server thread/WARN]: java.lang.IllegalArgumentException: Unable to read from java.io.DataInputStream@15517063
[13:15:55] [Server thread/WARN]: 	at MysqlPlayerDataBridge-v4.12.2.jar//net.craftersland.data.bridge.utils.nms.Version_1_20_R4.readNbt(Version_1_20_R4.java:143)
[13:15:55] [Server thread/WARN]: 	at MysqlPlayerDataBridge-v4.12.2.jar//net.craftersland.data.bridge.utils.nms.Version_1_20_R4.fromBase64(Version_1_20_R4.java:97)
[13:15:55] [Server thread/WARN]: 	at MysqlPlayerDataBridge-v4.12.2.jar//net.craftersland.data.bridge.events.handlers.InventoryDataHandler.setInventory(InventoryDataHandler.java:320)
[13:15:55] [Server thread/WARN]: 	at MysqlPlayerDataBridge-v4.12.2.jar//net.craftersland.data.bridge.events.handlers.InventoryDataHandler.setPlayerData(InventoryDataHandler.java:95)
[13:15:55] [Server thread/WARN]: 	at MysqlPlayerDataBridge-v4.12.2.jar//net.craftersland.data.bridge.runnables.InventorySyncTask$1.run(InventorySyncTask.java:62)
[13:15:55] [Server thread/WARN]: 	at org.bukkit.craftbukkit.scheduler.CraftTask.run(CraftTask.java:101)
[13:15:55] [Server thread/WARN]: 	at org.bukkit.craftbukkit.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:482)
[13:15:55] [Server thread/WARN]: 	at net.minecraft.server.MinecraftServer.tickChildren(MinecraftServer.java:1703)
[13:15:55] [Server thread/WARN]: 	at net.minecraft.server.dedicated.DedicatedServer.tickChildren(DedicatedServer.java:468)
[13:15:55] [Server thread/WARN]: 	at net.minecraft.server.MinecraftServer.tickServer(MinecraftServer.java:1575)
[13:15:55] [Server thread/WARN]: 	at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1235)
[13:15:55] [Server thread/WARN]: 	at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:326)
[13:15:55] [Server thread/WARN]: 	at java.base/java.lang.Thread.run(Thread.java:1583)
[13:15:55] [Server thread/WARN]: Caused by: java.lang.reflect.InvocationTargetException
[13:15:55] [Server thread/WARN]: 	at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:118)
[13:15:55] [Server thread/WARN]: 	at java.base/java.lang.reflect.Method.invoke(Method.java:580)
[13:15:55] [Server thread/WARN]: 	at MysqlPlayerDataBridge-v4.12.2.jar//net.craftersland.data.bridge.utils.nms.Version_1_20_R4.readNbt(Version_1_20_R4.java:141)
[13:15:55] [Server thread/WARN]: 	... 12 more
[13:15:55] [Server thread/WARN]: Caused by: net.minecraft.nbt.ReportedNbtException: Loading NBT data
[13:15:55] [Server thread/WARN]: 	at net.minecraft.nbt.NbtIo.readTagSafe(NbtIo.java:416)
[13:15:55] [Server thread/WARN]: 	at net.minecraft.nbt.NbtIo.readUnnamedTag(NbtIo.java:404)
[13:15:55] [Server thread/WARN]: 	at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
[13:15:55] [Server thread/WARN]: 	... 14 more
[13:15:55] [Server thread/WARN]: Caused by: java.io.EOFException
[13:15:55] [Server thread/WARN]: 	at java.base/java.io.DataInputStream.readUnsignedByte(DataInputStream.java:297)
[13:15:55] [Server thread/WARN]: 	at java.base/java.io.DataInputStream.readByte(DataInputStream.java:275)
[13:15:55] [Server thread/WARN]: 	at net.minecraft.nbt.ListTag$1.loadList(ListTag.java:31)
[13:15:55] [Server thread/WARN]: 	at net.minecraft.nbt.ListTag$1.load(ListTag.java:26)
[13:15:55] [Server thread/WARN]: 	at net.minecraft.nbt.ListTag$1.load(ListTag.java:17)
[13:15:55] [Server thread/WARN]: 	at net.minecraft.nbt.NbtIo.readTagSafe(NbtIo.java:410)
[13:15:55] [Server thread/WARN]: 	... 16 more
[13:15:55] [Server thread/INFO]: Phoenixfly1337 lost connection: Daten Synchronisation fehgeschlagen! Verbinde erneut oder Kontaktiere ein Teammitglied.
[13:15:55] [Server thread/INFO]: [TEAM] Owner | Phoenixfly1337 left the game
[13:15:55] [Server thread/WARN]: java.lang.IllegalArgumentException: Unable to read from java.io.DataInputStream@6e7fa9c0
[13:15:55] [Server thread/WARN]: 	at MysqlPlayerDataBridge-v4.12.2.jar//net.craftersland.data.bridge.utils.nms.Version_1_20_R4.readNbt(Version_1_20_R4.java:143)
[13:15:55] [Server thread/WARN]: 	at MysqlPlayerDataBridge-v4.12.2.jar//net.craftersland.data.bridge.utils.nms.Version_1_20_R4.fromBase64(Version_1_20_R4.java:97)
[13:15:55] [Server thread/WARN]: 	at MysqlPlayerDataBridge-v4.12.2.jar//net.craftersland.data.bridge.events.handlers.InventoryDataHandler.setArmor(InventoryDataHandler.java:399)
[13:15:55] [Server thread/WARN]: 	at MysqlPlayerDataBridge-v4.12.2.jar//net.craftersland.data.bridge.events.handlers.InventoryDataHandler.setPlayerData(InventoryDataHandler.java:96)
[13:15:55] [Server thread/WARN]: 	at MysqlPlayerDataBridge-v4.12.2.jar//net.craftersland.data.bridge.runnables.InventorySyncTask$1.run(InventorySyncTask.java:62)
[13:15:55] [Server thread/WARN]: 	at org.bukkit.craftbukkit.scheduler.CraftTask.run(CraftTask.java:101)
[13:15:55] [Server thread/WARN]: 	at org.bukkit.craftbukkit.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:482)
[13:15:55] [Server thread/WARN]: 	at net.minecraft.server.MinecraftServer.tickChildren(MinecraftServer.java:1703)
[13:15:55] [Server thread/WARN]: 	at net.minecraft.server.dedicated.DedicatedServer.tickChildren(DedicatedServer.java:468)
[13:15:55] [Server thread/WARN]: 	at net.minecraft.server.MinecraftServer.tickServer(MinecraftServer.java:1575)
[13:15:55] [Server thread/WARN]: 	at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1235)
[13:15:55] [Server thread/WARN]: 	at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:326)
[13:15:55] [Server thread/WARN]: 	at java.base/java.lang.Thread.run(Thread.java:1583)
[13:15:55] [Server thread/WARN]: Caused by: java.lang.reflect.InvocationTargetException
[13:15:55] [Server thread/WARN]: 	at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:118)
[13:15:55] [Server thread/WARN]: 	at java.base/java.lang.reflect.Method.invoke(Method.java:580)
[13:15:55] [Server thread/WARN]: 	at MysqlPlayerDataBridge-v4.12.2.jar//net.craftersland.data.bridge.utils.nms.Version_1_20_R4.readNbt(Version_1_20_R4.java:141)
[13:15:55] [Server thread/WARN]: 	... 12 more
[13:15:55] [Server thread/WARN]: Caused by: net.minecraft.nbt.ReportedNbtException: Loading NBT data
[13:15:55] [Server thread/WARN]: 	at net.minecraft.nbt.NbtIo.readTagSafe(NbtIo.java:416)
[13:15:55] [Server thread/WARN]: 	at net.minecraft.nbt.NbtIo.readUnnamedTag(NbtIo.java:404)
[13:15:55] [Server thread/WARN]: 	at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
[13:15:55] [Server thread/WARN]: 	... 14 more
[13:15:55] [Server thread/WARN]: Caused by: java.io.EOFException
[13:15:55] [Server thread/WARN]: 	at java.base/java.io.DataInputStream.readUnsignedByte(DataInputStream.java:297)
[13:15:55] [Server thread/WARN]: 	at java.base/java.io.DataInputStream.readByte(DataInputStream.java:275)
[13:15:55] [Server thread/WARN]: 	at net.minecraft.nbt.ListTag$1.loadList(ListTag.java:31)
[13:15:55] [Server thread/WARN]: 	at net.minecraft.nbt.ListTag$1.load(ListTag.java:26)
[13:15:55] [Server thread/WARN]: 	at net.minecraft.nbt.ListTag$1.load(ListTag.java:17)
[13:15:55] [Server thread/WARN]: 	at net.minecraft.nbt.NbtIo.readTagSafe(NbtIo.java:410)
[13:15:55] [Server thread/WARN]: 	... 16 more
[13:15:55] [Server thread/WARN]: [MysqlPlayerDataBridge] Task #3694 for MysqlPlayerDataBridge v4.12.2 generated an exception
java.lang.RuntimeException: Essentials API is called before Essentials is loaded.
	at EssentialsX-2.21.0-dev+81-cde7184.jar/com.earth2me.essentials.api.Economy.getUserByUUID(Economy.java:109) ~[EssentialsX-2.21.0-dev+81-cde7184.jar:?]
	at EssentialsX-2.21.0-dev+81-cde7184.jar/com.earth2me.essentials.api.Economy.getMoneyExact(Economy.java:160) ~[EssentialsX-2.21.0-dev+81-cde7184.jar:?]
	at EssentialsX-2.21.0-dev+81-cde7184.jar/com.earth2me.essentials.economy.vault.VaultEconomyProvider.getBalance(VaultEconomyProvider.java:116) ~[EssentialsX-2.21.0-dev+81-cde7184.jar:?]
	at MysqlPlayerDataBridge-v4.12.2.jar/net.craftersland.data.bridge.events.handlers.EconomyDataHandler.getLocalBalance(EconomyDataHandler.java:55) ~[MysqlPlayerDataBridge-v4.12.2.jar:?]
	at MysqlPlayerDataBridge-v4.12.2.jar/net.craftersland.data.bridge.events.PlayerDisconnect$1.run(PlayerDisconnect.java:67) ~[MysqlPlayerDataBridge-v4.12.2.jar:?]
	at org.bukkit.craftbukkit.scheduler.CraftTask.run(CraftTask.java:101) ~[paper-1.20.6.jar:git-Paper-62]
	at org.bukkit.craftbukkit.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:482) ~[paper-1.20.6.jar:git-Paper-62]
	at net.minecraft.server.MinecraftServer.tickChildren(MinecraftServer.java:1703) ~[paper-1.20.6.jar:git-Paper-62]
	at net.minecraft.server.dedicated.DedicatedServer.tickChildren(DedicatedServer.java:468) ~[paper-1.20.6.jar:git-Paper-62]
	at net.minecraft.server.MinecraftServer.tickServer(MinecraftServer.java:1575) ~[paper-1.20.6.jar:git-Paper-62]
	at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1235) ~[paper-1.20.6.jar:git-Paper-62]
	at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:326) ~[paper-1.20.6.jar:git-Paper-62]
	at java.base/java.lang.Thread.run(Thread.java:1583) ~[?:?]
```

Edit: This is the whole stacktrace for one player joining

**Comment by SyncCircle** [comment]
I have the same issue:

https://www.spigotmc.org/threads/mysql-player-data-bridge-paid.71612/page-137#post-4738065

**Comment by Fly1337** [comment]
Not quite, it looks like the issue above got fixed but there is another one which needs to be fixed

**Comment by SyncCircle** [comment]
> Not quite, it looks like the issue above got fixed but there is another one which needs to be fixed


Yes, because my error is different to yours.
