### ISSUE TITLE
Enchanted items return to their pre-enchantment state and item lost 

### ISSUE THREAD

**Issue by minamikana-git** [brunyman/MPDB#132]
![2024-06-19_14 50 18](https://github.com/brunyman/MPDB/assets/93361361/8cb82379-9b67-4eb4-a811-0a3cbff0f51c)
before
![2024-06-19_14 52 53](https://github.com/brunyman/MPDB/assets/93361361/dbacdf47-7b37-4828-93a8-4954635e08c5)
after

Server version

All Paper 1.21-21

This Picture is Survival Server.

**Comment by minamikana-git** [comment]
My proxy server is Velocity-3.3.0-SNAPSHOT-400
backend (main) server is All Paper 1.21-21

If you have any questions, just ask.

**Comment by minamikana-git** [comment]
this console message says:
! [Wed 14:29:34 WARN ] java.lang.IllegalStateException: Can't access registry ResourceKey[minecraft:root / minecraft:enchantment]; Can't access registry ResourceKey[minecraft:root / minecraft:enchantment]; Can't access registry ResourceKey[minecraft:root / minecraft:enchantment]; Can't access registry ResourceKey[minecraft:root / minecraft:enchantment]; Can't access registry ResourceKey[minecraft:root / minecraft:enchantment]; Can't access registry ResourceKey[minecraft:root / minecraft:enchantment]
! [Wed 14:29:34 WARN ]     at com.mojang.serialization.DataResult$Error.getOrThrow(DataResult.java:287)
! [Wed 14:29:34 WARN ]     at com.mojang.serialization.DataResult.getOrThrow(DataResult.java:81)
! [Wed 14:29:34 WARN ]     at net.minecraft.world.item.ItemStack.save(ItemStack.java:614)
! [Wed 14:29:34 WARN ]     at MysqlPlayerDataBridge-v4.14.0.jar//net.craftersland.data.bridge.utils.nms.Version_1_21_R1.toBase64(Version_1_21_R1.java:63)
! [Wed 14:29:34 WARN ]     at MysqlPlayerDataBridge-v4.14.0.jar//net.craftersland.data.bridge.events.handlers.InventoryDataHandler.onDataSaveFunction(InventoryDataHandler.java:181)
! [Wed 14:29:34 WARN ]     at MysqlPlayerDataBridge-v4.14.0.jar//net.craftersland.data.bridge.events.PlayerDisconnect$1$1.run(PlayerDisconnect.java:78)
! [Wed 14:29:34 WARN ]     at org.bukkit.craftbukkit.scheduler.CraftTask.run(CraftTask.java:101)
! [Wed 14:29:34 WARN ]     at org.bukkit.craftbukkit.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:57)
! [Wed 14:29:34 WARN ]     at com.destroystokyo.paper.ServerSchedulerReportingWrapper.run(ServerSchedulerReportingWrapper.java:22)

[14:29]
! [Wed 14:29:34 WARN ]     at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
! [Wed 14:29:34 WARN ]     at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
! [Wed 14:29:34 WARN ]     at java.base/java.lang.Thread.run(Thread.java:1570)
! [Wed 14:29:34 WARN ] java.lang.IllegalStateException: Can't access registry ResourceKey[minecraft:root / minecraft:enchantment]; Can't access registry ResourceKey[minecraft:root / minecraft:enchantment]; Can't access registry ResourceKey[minecraft:root / minecraft:enchantment]; Can't access registry ResourceKey[minecraft:root / minecraft:enchantment]
! [Wed 14:29:34 WARN ]     at com.mojang.serialization.DataResult$Error.getOrThrow(DataResult.java:287)
! [Wed 14:29:34 WARN ]     at com.mojang.serialization.DataResult.getOrThrow(DataResult.java:81)
! [Wed 14:29:34 WARN ]     at net.minecraft.world.item.ItemStack.save(ItemStack.java:614)
! [Wed 14:29:34 WARN ]     at MysqlPlayerDataBridge-v4.14.0.jar//net.craftersland.data.bridge.utils.nms.Version_1_21_R1.toBase64(Version_1_21_R1.java:63)
! [Wed 14:29:34 WARN ]     at MysqlPlayerDataBridge-v4.14.0.jar//net.craftersland.data.bridge.events.handlers.InventoryDataHandler.onDataSaveFunction(InventoryDataHandler.java:196)
! [Wed 14:29:34 WARN ]     at MysqlPlayerDataBridge-v4.14.0.jar//net.craftersland.data.bridge.events.PlayerDisconnect$1$1.run(PlayerDisconnect.java:78)
! [Wed 14:29:34 WARN ]     at org.bukkit.craftbukkit.scheduler.CraftTask.run(CraftTask.java:101)
! [Wed 14:29:34 WARN ]     at org.bukkit.craftbukkit.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:57)
! [Wed 14:29:34 WARN ]     at com.destroystokyo.paper.ServerSchedulerReportingWrapper.run(ServerSchedulerReportingWrapper.java:22)
! [Wed 14:29:34 WARN ]     at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
! [Wed 14:29:34 WARN ]     at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
[14:29]
! [Wed 14:29:34 WARN ]     at java.base/java.lang.Thread.run(Thread.java:1570)

**Comment by minamikana-git** [comment]
Client: Fabric Minecraft 1.20.6

**Comment by flysig** [comment]
By rolling back the server the enchantments come back. So you only need to write a new translater and the enchantments are not lost.

**Comment by interacp** [comment]
This is currently happening on the 1.21 server. The log file above is confirmed to have been uploaded, so I hope for a quick update from the development team.

**Comment by Gingied** [comment]
Still happening in latest... will we get a fix for this? The (paid btw) project is kinda dead in the water until it- y'know- stores player data as intended.

ETA: Paper/purpur 1.20.5+ tested, ended up reverting to vanilla and loading a backup of playerdata from a few hours ago.

**Comment by neco222** [comment]
The exact same problem occurred. 
Stack items are now one of all, and enchantments are all gone.
