### ISSUE TITLE
MysqlPlayerDataBridge - Player data not saved when kicked or disconnected :null

### ISSUE THREAD

**Issue by fuchsiaa** [brunyman/MPDB#17]
Hello,

We kinda lost how to fix the errors hope we can get some help here. 
- FTB Infinity Evolved 1.7 - 3.10
- Thermos 1.7.10-1614.58

We have 2 issues:
The first one is that the data is not saved when a player disconnects from the server and we get the following error,

> [19:49:50] [Server thread/INFO]: <PLAYER> lost connection: Disconnected
[19:49:50] [Server thread/INFO]: <PLAYER>left the game.
[19:49:50] [Craft Scheduler Thread - 12/WARN]: Exception in thread "Craft Scheduler Thread - 12" 
[19:49:50] [Craft Scheduler Thread - 12/WARN]: org.apache.commons.lang.UnhandledException: Plugin MysqlPlayerDataBridge v3.35.0 generated an exception while executing task 1645
	at org.bukkit.craftbukkit.v1_7_R4.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:57)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)
Caused by: java.lang.NoSuchMethodError: com.mojang.authlib.GameProfile.<init>(Ljava/lang/String;Ljava/lang/String;)V
	at net.craftersland.data.bridge.utils.nms.Version_1_7_R4_Kauldron.loadPlayer(Version_1_7_R4_Kauldron.java:74)
	at net.craftersland.data.bridge.events.PlayerDisconnect$1.run(PlayerDisconnect.java:39)
	at org.bukkit.craftbukkit.v1_7_R4.scheduler.CraftTask.run(CraftTask.java:71)
	at org.bukkit.craftbukkit.v1_7_R4.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:53)
	... 3 more

The second issue is when the server restarts and when we use /mpdb saveAndKick.

> [20:05:58] [Server thread/INFO]: [MysqlPlayerDataBridge] Saving data and kicking all players...
[20:05:58] [Server thread/ERROR]: null
org.bukkit.command.CommandException: Unhandled exception executing command 'mpdb' in plugin MysqlPlayerDataBridge v3.35.0
	at org.bukkit.command.PluginCommand.execute(PluginCommand.java:46) ~[PluginCommand.class:1.7.10-1614.58]
	at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:181) ~[SimpleCommandMap.class:1.7.10-1614.58]
	at org.bukkit.craftbukkit.v1_7_R4.CraftServer.dispatchCommand(CraftServer.java:740) ~[CraftServer.class:1.7.10-1614.58]
	at net.minecraft.network.NetHandlerPlayServer.func_147361_d(NetHandlerPlayServer.java:1370) [nh.class:?]
	at net.minecraft.network.NetHandlerPlayServer.func_147354_a(NetHandlerPlayServer.java:1107) [nh.class:?]
	at net.minecraft.network.play.client.C01PacketChatMessage.func_148833_a(C01PacketChatMessage.java:38) [ir.class:?]
	at net.minecraft.network.play.client.C01PacketChatMessage.func_148833_a(C01PacketChatMessage.java:53) [ir.class:?]
	at net.minecraft.network.NetworkManager.func_74428_b(NetworkManager.java:245) [ej.class:?]
	at net.minecraft.network.NetworkSystem.func_151269_c(NetworkSystem.java:181) [nc.class:?]
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:1023) [MinecraftServer.class:?]
	at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:432) [lt.class:?]
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:841) [MinecraftServer.class:?]
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:693) [MinecraftServer.class:?]
	at java.lang.Thread.run(Unknown Source) [?:1.8.0_261]
Caused by: java.lang.NoSuchMethodError: com.mojang.authlib.GameProfile.<init>(Ljava/lang/String;Ljava/lang/String;)V
	at net.craftersland.data.bridge.utils.nms.Version_1_7_R4_Kauldron.loadPlayer(Version_1_7_R4_Kauldron.java:74) ~[?:?]
	at net.craftersland.data.bridge.commands.handlers.SaveAndKickCmd.runCommand(SaveAndKickCmd.java:40) ~[?:?]
	at net.craftersland.data.bridge.commands.Mpdb.onCommand(Mpdb.java:47) ~[?:?]
	at org.bukkit.command.PluginCommand.execute(PluginCommand.java:44) ~[PluginCommand.class:1.7.10-1614.58]
	... 13 more

Greetings. 
Glad to hear from you.

**Comment by fuchsiaa** [comment]
**HiHi,**
**The player data is saved in the database** 

**When we do /mpdb importdata player.**

> [21:36:57] [Server thread/INFO]: <player> issued server command: /mpdb importdata
[21:36:57] [Craft Scheduler Thread - 40/INFO]: [MysqlPlayerDataBridge] Starting import data process!
[21:36:57] [Craft Scheduler Thread - 40/INFO]: [MysqlPlayerDataBridge] Processing 4 players...
[21:36:57] [Craft Scheduler Thread - 40/INFO]:  Import data progress: 1/4
[21:36:57] [Craft Scheduler Thread - 40/WARN]: Exception in thread "Craft Scheduler Thread - 40" 
[21:36:57] [Craft Scheduler Thread - 40/WARN]: org.apache.commons.lang.UnhandledException: Plugin MysqlPlayerDataBridge v3.35.0 generated an exception while executing task 10368
	at org.bukkit.craftbukkit.v1_7_R4.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:57)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)
Caused by: java.lang.NoSuchMethodError: com.mojang.authlib.GameProfile.<init>(Ljava/lang/String;Ljava/lang/String;)V
	at net.craftersland.data.bridge.utils.nms.Version_1_7_R4_Kauldron.loadPlayer(Version_1_7_R4_Kauldron.java:74)
	at net.craftersland.data.bridge.commands.handlers.ImportCmd$1.run(ImportCmd.java:39)
	at org.bukkit.craftbukkit.v1_7_R4.scheduler.CraftTask.run(CraftTask.java:71)
	at org.bukkit.craftbukkit.v1_7_R4.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:53)
	... 3 more

**We disabled/enabled everything same out come 
We did some more searching for errors, hope this helps** 


> [16:46:13] [Server thread/INFO]: [MysqlPlayerDataBridge] Enabling MysqlPlayerDataBridge v3.35.0
[16:46:13] [Server thread/INFO]: [MysqlPlayerDataBridge] Loading the config file...
[16:46:13] [Server thread/INFO]: [MysqlPlayerDataBridge] Vault dependency found.
[16:46:13] [Server thread/INFO]: [MysqlPlayerDataBridge] Using economy system: Essentials Economy
[16:46:13] [Server thread/INFO]: [MysqlPlayerDataBridge] Compatible server version detected: 1.7.10
[16:46:13] [Server thread/INFO]: [MysqlPlayerDataBridge] Cauldron server detected. ProtocolLib dependency is required!
[16:46:13] [Server thread/INFO]: [MysqlPlayerDataBridge] ProtocolLib dependency found.
[16:46:13] [Server thread/INFO]: [MysqlPlayerDataBridge] Connecting to the database...
[16:46:13] [Server thread/INFO]: [MysqlPlayerDataBridge] Database connection successfull!
[16:46:13] [Server thread/INFO]: [MysqlPlayerDataBridge] Data save task is enabled.
[16:46:13] [Server thread/INFO]: [MysqlPlayerDataBridge] Sync inventory is enabled.
[16:46:13] [Server thread/INFO]: [MysqlPlayerDataBridge] Sync gamemode is disabled.
[16:46:13] [Server thread/INFO]: [MysqlPlayerDataBridge] Sync armor is enabled.
[16:46:13] [Server thread/INFO]: [MysqlPlayerDataBridge] Sync enderchest is disabled.
[16:46:13] [Server thread/INFO]: [MysqlPlayerDataBridge] Sync experience is enabled.
[16:46:13] [Server thread/INFO]: [MysqlPlayerDataBridge] Sync active potion effects is disabled.
[16:46:13] [Server thread/INFO]: [MysqlPlayerDataBridge] Sync players health  is disabled.
[16:46:13] [Server thread/INFO]: [MysqlPlayerDataBridge] Sync players food is disabled.
[16:46:13] [Server thread/INFO]: [MysqlPlayerDataBridge] Sync players air is disabled.
[16:46:13] [Server thread/INFO]: [MysqlPlayerDataBridge] Sync players location is disabled.
[16:46:13] [Server thread/INFO]: [MysqlPlayerDataBridge] Sync players bed location is disabled.
[16:46:13] [Server thread/INFO]: [MysqlPlayerDataBridge] Sync economy is disabled.
[16:46:13] [Server thread/ERROR]: [MysqlPlayerDataBridge] Plugin MysqlPlayerDataBridge v3.35.0 has failed to register events for class net.craftersland.data.bridge.events.PickupItem because org/bukkit/event/entity/EntityPickupItemEvent does not exist.
[16:46:13] [Server thread/INFO]: [MysqlPlayerDataBridge] MysqlPlayerDataBridge loaded successfully!


**Greetings.
Glad to hear from you.**

**Comment by terencekam** [comment]
there are the same issuse on my server
plz fix asap

**Comment by fuchsiaa** [comment]
We can w8 a long time for that.

**Comment by Maxafrost** [comment]
I too have the same issue
```
[01:05:19] [Server thread/INFO]: Maxafrost lost connection: Disconnected
[01:05:20] [Server thread/INFO]: Maxafrost left the game.
[01:05:20] [Craft Scheduler Thread - 3/WARN]: Exception in thread "Craft Scheduler Thread - 3" 
[01:05:20] [Craft Scheduler Thread - 3/WARN]: org.apache.commons.lang.UnhandledException: Plugin MysqlPlayerDataBridge v3.35.1 generated an exception while executing task 25
	at org.bukkit.craftbukkit.v1_7_R4.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:57)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)
Caused by: java.lang.NoSuchMethodError: com.mojang.authlib.GameProfile.<init>(Ljava/lang/String;Ljava/lang/String;)V
	at net.craftersland.data.bridge.utils.nms.Version_1_7_R4_Kauldron.loadPlayer(Version_1_7_R4_Kauldron.java:74)
	at net.craftersland.data.bridge.events.PlayerDisconnect$1.run(PlayerDisconnect.java:39)
	at org.bukkit.craftbukkit.v1_7_R4.scheduler.CraftTask.run(CraftTask.java:71)
	at org.bukkit.craftbukkit.v1_7_R4.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:53)
	... 3 more
```
I'm using a modified version of FTB Infinity Evolved
