### ISSUE TITLE
Copying

### ISSUE THREAD

**Issue by botany111** [brunyman/MPDB#2]
Player puts items in the box
Leave server immediately
You will get items in the box when you log in again

**Comment by botany111** [comment]
Occurs when the server is delayed

**Comment by brunyman** [comment]
Hi, I need more details about your server configuration, version, other plugins, logs.
I cannot reproduce this on my server, it always runs fine.

**Comment by botany111** [comment]
25.02 09:22:11 [Server] WARN [MysqlPlayerDataBridge] Plugin MysqlPlayerDataBridge v3.33.0 generated an exception while executing task 114
25.02 09:22:11 [Server] INFO java.util.ConcurrentModificationException: null
25.02 09:22:11 [Server] INFO at java.util.HashMap$HashIterator.nextNode(HashMap.java:1445) ~[?:1.8.0_222]
25.02 09:22:11 [Server] INFO at java.util.HashMap$KeyIterator.next(HashMap.java:1469) ~[?:1.8.0_222]
25.02 09:22:11 [Server] INFO at net.craftersland.data.bridge.runnables.DataSaveTask.saveOnlinePlayersData(DataSaveTask.java:59) ~[?:?]
25.02 09:22:11 [Server] INFO at net.craftersland.data.bridge.runnables.DataSaveTask$1.run(DataSaveTask.java:37) ~[?:?]
25.02 09:22:11 [Server] INFO at org.bukkit.craftbukkit.v1_15_R1.scheduler.CraftTask.run(CraftTask.java:84) ~[patched_1.15.2.jar:git-Paper-118]
25.02 09:22:11 [Server] INFO at org.bukkit.craftbukkit.v1_15_R1.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:54) ~[patched_1.15.2.jar:git-Paper-118]
25.02 09:22:11 [Server] INFO at com.destroystokyo.paper.ServerSchedulerReportingWrapper.run(ServerSchedulerReportingWrapper.java:22) ~[patched_1.15.2.jar:git-Paper-118]
25.02 09:22:11 [Server] INFO at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [?:1.8.0_222]
25.02 09:22:11 [Server] INFO at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [?:1.8.0_222]
25.02 09:22:11 [Server] INFO at java.lang.Thread.run(Thread.java:748) [?:1.8.0_222]

**Comment by botany111** [comment]
Whether it can increase
When the player leaves the box
Save player information

**Comment by brunyman** [comment]
I can't really understand, by box you mean server?

I still need more info about server version, a full log.
