### ISSUE TITLE
ERROR: Could not pass event PlayerExchangeShopEvent to MysqlPlayerDataBridge

### ISSUE THREAD

**Issue by lordvarus** [brunyman/MPDB#39]
**Shop Plugin: https://www.spigotmc.org/resources/shop-a-simple-intuitive-shop-plugin.9628/**

Could not pass event PlayerExchangeShopEvent to MysqlPlayerDataBridge v3.35.1
java.lang.NoSuchMethodError: 'com.snowgears.shop.ShopObject com.snowgears.shop.event.PlayerExchangeShopEvent.getShop()'
	at net.craftersland.data.bridge.events.ShopSupport.onShopTransaction(ShopSupport.java:25) ~[?:?]
	at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor612.execute(Unknown Source) ~[?:?]
	at org.bukkit.plugin.EventExecutor.lambda$create$1(EventExecutor.java:69) ~[patched_1.16.5.jar:git-Purpur-978]
	at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:80) ~[patched_1.16.5.jar:git-Purpur-978]
	at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[patched_1.16.5.jar:git-Purpur-978]
	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:607) ~[patched_1.16.5.jar:git-Purpur-978]
	at com.snowgears.shop.SellShop.executeTransaction(SellShop.java:93) ~[?:?]
	at com.snowgears.shop.listener.TransactionListener.executeTransaction(TransactionListener.java:131) ~[?:?]
	at com.snowgears.shop.listener.TransactionListener.onShopSignClick(TransactionListener.java:116) ~[?:?]
	at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor568.execute(Unknown Source) ~[?:?]
	at org.bukkit.plugin.EventExecutor.lambda$create$1(EventExecutor.java:69) ~[patched_1.16.5.jar:git-Purpur-978]
	at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:80) ~[patched_1.16.5.jar:git-Purpur-978]
	at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[patched_1.16.5.jar:git-Purpur-978]
	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:607) ~[patched_1.16.5.jar:git-Purpur-978]
	at org.bukkit.craftbukkit.v1_16_R3.event.CraftEventFactory.callPlayerInteractEvent(CraftEventFactory.java:528) ~[patched_1.16.5.jar:git-Purpur-978]
	at net.minecraft.server.v1_16_R3.PlayerInteractManager.a(PlayerInteractManager.java:497) ~[patched_1.16.5.jar:git-Purpur-978]
	at net.minecraft.server.v1_16_R3.PlayerConnection.a(PlayerConnection.java:1635) ~[patched_1.16.5.jar:git-Purpur-978]
	at xuan.cat.xuancatapi.code.paper.v1_16_R3.nms.entity.CodeExtendPlayerConnection.packetIn(CodeExtendPlayerConnection.java:765) ~[?:?]
	at xuan.cat.xuancatapi.code.paper.v1_16_R3.nms.entity.CodeExtendPlayerConnection.packetIn(CodeExtendPlayerConnection.java:604) ~[?:?]
	at xuan.cat.xuancatapi.code.paper.v1_16_R3.nms.entity.CodeExtendPlayerConnection.a(CodeExtendPlayerConnection.java:112) ~[?:?]
	at net.minecraft.server.v1_16_R3.PacketPlayInUseItem.a(PacketPlayInUseItem.java:27) ~[patched_1.16.5.jar:git-Purpur-978]
	at net.minecraft.server.v1_16_R3.PacketPlayInUseItem.a(PacketPlayInUseItem.java:5) ~[patched_1.16.5.jar:git-Purpur-978]
	at net.minecraft.server.v1_16_R3.PlayerConnectionUtils.lambda$ensureMainThread$1(PlayerConnectionUtils.java:43) ~[patched_1.16.5.jar:git-Purpur-978]
	at net.minecraft.server.v1_16_R3.TickTask.run(SourceFile:18) ~[patched_1.16.5.jar:git-Purpur-978]
	at net.minecraft.server.v1_16_R3.IAsyncTaskHandler.executeTask(IAsyncTaskHandler.java:136) ~[patched_1.16.5.jar:git-Purpur-978]
	at net.minecraft.server.v1_16_R3.IAsyncTaskHandlerReentrant.executeTask(SourceFile:23) ~[patched_1.16.5.jar:git-Purpur-978]
	at net.minecraft.server.v1_16_R3.IAsyncTaskHandler.executeNext(IAsyncTaskHandler.java:109) ~[patched_1.16.5.jar:git-Purpur-978]
	at net.minecraft.server.v1_16_R3.MinecraftServer.bb(MinecraftServer.java:1207) ~[patched_1.16.5.jar:git-Purpur-978]
	at net.minecraft.server.v1_16_R3.MinecraftServer.executeNext(MinecraftServer.java:1200) ~[patched_1.16.5.jar:git-Purpur-978]
	at net.minecraft.server.v1_16_R3.IAsyncTaskHandler.awaitTasks(IAsyncTaskHandler.java:119) ~[patched_1.16.5.jar:git-Purpur-978]
	at net.minecraft.server.v1_16_R3.MinecraftServer.sleepForTick(MinecraftServer.java:1176) ~[patched_1.16.5.jar:git-Purpur-978]
	at net.minecraft.server.v1_16_R3.MinecraftServer.w(MinecraftServer.java:1020) ~[patched_1.16.5.jar:git-Purpur-978]
	at net.minecraft.server.v1_16_R3.MinecraftServer.lambda$a$0(MinecraftServer.java:176) ~[patched_1.16.5.jar:git-Purpur-978]
	at java.lang.Thread.run(Unknown Source) [?:?]

**Comment by lordvarus** [comment]
Your plugin is trying to log a custom event that only exists in the shop plugin (PlayerExchangeShopEvent). You should check if an event exists before trying to log it. Please fix it soon!
