### ISSUE TITLE
Server unable to shutdown with Dungeonsxl on the server

### ISSUE THREAD

**Issue by Frerduro** [brunyman/MPDB#7]
Hello I am unable to stop my server if dungeonsxl is on the server it will just hang there until we kill the server
`stop
[17:03:22 INFO]: [MysqlPlayerDataBridge] Saving data and kicking all players...
[17:03:22 ERROR]: Could not pass event ServerCommandEvent to MysqlPlayerDataBridge v3.34.1
java.lang.NullPointerException: null
at net.craftersland.data.bridge.events.DungeonsXL_Support.isPlayerInDungeon(DungeonsXL_Support.java:24) ~[?:?]
at net.craftersland.data.bridge.events.DungeonsXL_Support.checkPlayer(DungeonsXL_Support.java:28) ~[?:?]
at net.craftersland.data.bridge.events.handlers.InventoryDataHandler.onDataSaveFunction(InventoryDataHandler.java:164) ~[?:?]
at net.craftersland.data.bridge.commands.handlers.SaveAndKickCmd.runCommand(SaveAndKickCmd.java:61) ~[?:?]
at net.craftersland.data.bridge.events.ConsoleCommand.onCmd(ConsoleCommand.java:27) ~[?:?]
at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor441.execute(Unknown Source) ~[?:?]
at org.bukkit.plugin.EventExecutor.lambda$create$1(EventExecutor.java:69) ~[patched_1.16.1.jar:git-Paper-135]
at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:80) ~[patched_1.16.1.jar:git-Paper-135]
at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[patched_1.16.1.jar:git-Paper-135]
at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:607) ~[patched_1.16.1.jar:git-Paper-135]
at net.minecraft.server.v1_16_R1.DedicatedServer.handleCommandQueue(DedicatedServer.java:406) ~[patched_1.16.1.jar:git-Paper-135]
at net.minecraft.server.v1_16_R1.DedicatedServer.b(DedicatedServer.java:378) ~[patched_1.16.1.jar:git-Paper-135]
at net.minecraft.server.v1_16_R1.MinecraftServer.a(MinecraftServer.java:1213) ~[patched_1.16.1.jar:git-Paper-135]
at net.minecraft.server.v1_16_R1.MinecraftServer.v(MinecraftServer.java:1001) ~[patched_1.16.1.jar:git-Paper-135]
at net.minecraft.server.v1_16_R1.MinecraftServer.lambda$a$0(MinecraftServer.java:177) ~[patched_1.16.1.jar:git-Paper-135]
at java.lang.Thread.run(Thread.java:748) [?:1.8.0_262]`

**Comment by brunyman** [comment]
The entire log may be very useful, I wonder if DungeonsXL_Support plugin got disabled before MPDB plugin and that could cause the error

**Comment by brunyman** [comment]
I don't have dungeon setup to test this, can you please post a full server log so I can see what happens before this error, I need to see the context to understand what happened to provide a proper fix. Thanks

**Comment by Frerduro** [comment]
https://gist.github.com/Frerduro/87613948c76212201aff4e004f1052db here you go. the server is also erroring out everytime it tries to save a players inventory so everytime someone leaves their inventory isn't being saved

**Comment by brunyman** [comment]
It's missing the plugin loading part, is DungeonsXL plugin successfully enabled?

**Comment by brunyman** [comment]
I did some improvements, please test MPDB version 3.34.2 and let me know if you still have this issue

**Comment by Frerduro** [comment]
good news just updated and player data is now saving and we can now shutdown our server without killing it. Thanks for your help.

**Comment by brunyman** [comment]
Good to hear, thanks
