### ISSUE TITLE
BUG

### ISSUE THREAD

**Issue by OshinoLin** [brunyman/MPDB#72]
[23:07:07 ERROR]: Could not pass event ServerCommandEvent to MysqlPlayerDataBridge v4.2.0
java.lang.NullPointerException: Cannot invoke "net.minecraft.server.level.WorldServer.v()" because "world" is null
        at net.minecraft.server.level.ServerPlayer.<init>(ServerPlayer.java:265) ~[?:?]
        at net.craftersland.data.bridge.utils.nms.Version_1_18_R2.loadPlayer(Version_1_18_R2.java:135) ~[MysqlPlayerDataBridge-v4.2.0.jar:?]
        at net.craftersland.data.bridge.commands.handlers.SaveAndKickCmd.runCommand(SaveAndKickCmd.java:40) ~[MysqlPlayerDataBridge-v4.2.0.jar:?]
        at net.craftersland.data.bridge.events.ConsoleCommand.onCmd(ConsoleCommand.java:27) ~[MysqlPlayerDataBridge-v4.2.0.jar:?]
        at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor382.execute(Unknown Source) ~[?:?]
        at org.bukkit.plugin.EventExecutor.lambda$create$1(EventExecutor.java:75) ~[purpur-api-1.18.2-R0.1-SNAPSHOT.jar:?]
        at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:76) ~[purpur-api-1.18.2-R0.1-SNAPSHOT.jar:git-Purpur-1584]
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[purpur-api-1.18.2-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:631) ~[purpur-api-1.18.2-R0.1-SNAPSHOT.jar:?]
        at net.minecraft.server.dedicated.DedicatedServer.handleConsoleInputs(DedicatedServer.java:544) ~[purpur-1.18.2.jar:git-Purpur-1584]
        at net.minecraft.server.dedicated.DedicatedServer.tickChildren(DedicatedServer.java:523) ~[purpur-1.18.2.jar:git-Purpur-1584]
        at net.minecraft.server.MinecraftServer.tickServer(MinecraftServer.java:1485) ~[purpur-1.18.2.jar:git-Purpur-1584]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1248) ~[purpur-1.18.2.jar:git-Purpur-1584]
        at net.minecraft.server.MinecraftServer.lambda$spin$1(MinecraftServer.java:322) ~[purpur-1.18.2.jar:git-Purpur-1584]
        at java.lang.Thread.run(Thread.java:833) ~[?:?]
>

**Comment by brunyman** [comment]
Fixed in latest version
