### ISSUE TITLE
Error: Cannot invoke "net.minecraft.server.level.WorldServer.v()" because "world" is null

### ISSUE THREAD

**Issue by ofunny** [brunyman/MPDB#73]
I get the following error on my lobby server whenever a player leaves the server.
(For some reason it does only appear on the lobby server and not on any of my other servers. The lobby server has no extra plugins what are not also available on the other servers so it may be related to the server setup itself but I could no figure it out).

`[07:19:59 ERROR]: Could not pass event InventoryCloseEvent to MysqlPlayerDataBridge v4.2.0
java.lang.NoClassDefFoundError: net/craftersland/data/bridge/events/InventoryClose$1
        at net.craftersland.data.bridge.events.InventoryClose.onInventoryClose(InventoryClose.java:29) ~[MysqlPlayerDataBridge-v4.2.0.jar:?]
        at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor68.execute(Unknown Source) ~[?:?]
        at org.bukkit.plugin.EventExecutor.lambda$create$1(EventExecutor.java:75) ~[paper-api-1.18.2-R0.1-SNAPSHOT.jar:?]
        at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:76) ~[paper-api-1.18.2-R0.1-SNAPSHOT.jar:git-Paper-252]
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[paper-api-1.18.2-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:629) ~[paper-api-1.18.2-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.craftbukkit.v1_18_R2.event.CraftEventFactory.handleInventoryCloseEvent(CraftEventFactory.java:1532) ~[paper-1.18.2.jar:git-Paper-252]
        at net.minecraft.server.level.ServerPlayer.closeContainer(ServerPlayer.java:1573) ~[?:?]
        at org.bukkit.craftbukkit.v1_18_R2.entity.CraftHumanEntity.closeInventory(CraftHumanEntity.java:535) ~[paper-1.18.2.jar:git-Paper-252]
        at org.black_ixx.bossshop.core.BSBuy.purchase(BSBuy.java:493) ~[BossShopPro.jar:?]
        at org.black_ixx.bossshop.core.BSBuy.purchaseTask(BSBuy.java:449) ~[BossShopPro.jar:?]
        at org.black_ixx.bossshop.core.BSBuy.purchaseTry(BSBuy.java:423) ~[BossShopPro.jar:?]
        at org.black_ixx.bossshop.core.BSBuy.click(BSBuy.java:392) ~[BossShopPro.jar:?]
        at org.black_ixx.bossshop.listeners.InventoryListener.purchase(InventoryListener.java:189) ~[BossShopPro.jar:?]
        at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor468.execute(Unknown Source) ~[?:?]
        at org.bukkit.plugin.EventExecutor.lambda$create$1(EventExecutor.java:75) ~[paper-api-1.18.2-R0.1-SNAPSHOT.jar:?]
        at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:76) ~[paper-api-1.18.2-R0.1-SNAPSHOT.jar:git-Paper-252]
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[paper-api-1.18.2-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:629) ~[paper-api-1.18.2-R0.1-SNAPSHOT.jar:?]
        at net.minecraft.server.network.ServerGamePacketListenerImpl.handleContainerClick(ServerGamePacketListenerImpl.java:2860) ~[?:?]
        at net.minecraft.network.protocol.game.ServerboundContainerClickPacket.handle(ServerboundContainerClickPacket.java:58) ~[?:?]
        at net.minecraft.network.protocol.game.ServerboundContainerClickPacket.handle(ServerboundContainerClickPacket.java:13) ~[?:?]
        at net.minecraft.network.protocol.PacketUtils.lambda$ensureRunningOnSameThread$1(PacketUtils.java:51) ~[?:?]
        at net.minecraft.server.TickTask.run(TickTask.java:18) ~[paper-1.18.2.jar:git-Paper-252]
        at net.minecraft.util.thread.BlockableEventLoop.doRunTask(BlockableEventLoop.java:153) ~[?:?]
        at net.minecraft.util.thread.ReentrantBlockableEventLoop.doRunTask(ReentrantBlockableEventLoop.java:23) ~[?:?]
        at net.minecraft.server.MinecraftServer.doRunTask(MinecraftServer.java:1399) ~[paper-1.18.2.jar:git-Paper-252]
        at net.minecraft.server.MinecraftServer.d(MinecraftServer.java:188) ~[paper-1.18.2.jar:git-Paper-252]
        at net.minecraft.util.thread.BlockableEventLoop.pollTask(BlockableEventLoop.java:126) ~[?:?]
        at net.minecraft.server.MinecraftServer.pollTaskInternal(MinecraftServer.java:1376) ~[paper-1.18.2.jar:git-Paper-252]
        at net.minecraft.server.MinecraftServer.pollTask(MinecraftServer.java:1369) ~[paper-1.18.2.jar:git-Paper-252]
        at net.minecraft.util.thread.BlockableEventLoop.managedBlock(BlockableEventLoop.java:136) ~[?:?]
        at net.minecraft.server.MinecraftServer.waitUntilNextTick(MinecraftServer.java:1347) ~[paper-1.18.2.jar:git-Paper-252]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1229) ~[paper-1.18.2.jar:git-Paper-252]
        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:315) ~[paper-1.18.2.jar:git-Paper-252]
        at java.lang.Thread.run(Thread.java:833) ~[?:?]
Caused by: java.lang.ClassNotFoundException: net.craftersland.data.bridge.events.InventoryClose$1
        ... 36 more
[07:19:59 INFO]: ofunny lost connection: Disconnected
[07:19:59 INFO]: [DiscordSRV] Player ofunny quit with silent quitting permission, not sending a quit message
[07:19:59 INFO]: ofunny left the game
[07:19:59 WARN]: [MysqlPlayerDataBridge] Error getting player inventory over NMS on player Disconnect, getting it over Spigot API instead. Player: ofunny Error: Cannot invoke "net.minecraft.server.level.WorldServer.v()" because "world" is null
> 
`
MySQL Player Data Bridge 4.2.0
Paper 1.18.2 #252

Would be nice if you could fix it.
I use "MySQL Player Data Bridge" for economy sync only – otherwise I have to move on to another plugin since is not the first problem now and the support is actually dead …

**Comment by motz0815** [comment]
Yeah, I'm having exactly the same problem

**Comment by JeffHD** [comment]
Same issue here. It seems to come from the world name. I have the plugin on 4 Server and on 3 of them i become the error. The 3 with the error don't have a world named world. so maybe that is the problem

**Comment by motz0815** [comment]
> Same issue here. It seems to come from the world name. I have the plugin on 4 Server and on 3 of them i become the error. The 3 with the error don't have a world named world. so maybe that is the problem

My worlds are all just named world, so that can't be the issue.

**Comment by lerndmina** [comment]
I have the same issue.

**Comment by brunyman** [comment]
**Fixed in version 4.4.0 and up**
