### ISSUE TITLE
Data not Syncing to 1 server 

### ISSUE THREAD

**Issue by HiveHosting** [brunyman/MPDB#76]
after having multiple issues we started rebuilding the server to remove any issues encountered but with the data sync keep running in to the same issue hope to get some help. 

[09:56:56 INFO]: UUID of player Theprof01 is 804e12a9-cc4e-4a91-bf08-03c5a7dabeb6
[09:56:56 INFO]: Theprof01 joined the game
[09:56:56 INFO]: Theprof01[/82.176.24.124:65020] logged in with entity id 1123 at ([world]437.8627081766076, 77.31262463286917, -88.23711594869452)
[09:56:56 WARN]: [MysqlPlayerDataBridge] Task #19241 for MysqlPlayerDataBridge v4.2.0 generated an exception
java.lang.NoSuchMethodError: 'boolean net.minecraft.nbt.NBTTagCompound.f()'
	at net.craftersland.data.bridge.utils.nms.Version_1_17_R1.fromBase64(Version_1_17_R1.java:91) ~[MysqlPlayerDataBridge-v4.2.0.jar:?]
	at net.craftersland.data.bridge.events.handlers.InventoryDataHandler.setInventory(InventoryDataHandler.java:312) ~[MysqlPlayerDataBridge-v4.2.0.jar:?]
	at net.craftersland.data.bridge.events.handlers.InventoryDataHandler.setPlayerData(InventoryDataHandler.java:95) ~[MysqlPlayerDataBridge-v4.2.0.jar:?]
	at net.craftersland.data.bridge.events.handlers.InventoryDataHandler$2.run(InventoryDataHandler.java:239) ~[MysqlPlayerDataBridge-v4.2.0.jar:?]
	at org.bukkit.craftbukkit.v1_17_R1.scheduler.CraftTask.run(CraftTask.java:101) ~[patched_1.17.1.jar:git-Paper-409]
	at org.bukkit.craftbukkit.v1_17_R1.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:483) ~[patched_1.17.1.jar:git-Paper-409]
	at net.minecraft.server.MinecraftServer.tickChildren(MinecraftServer.java:1567) ~[patched_1.17.1.jar:git-Paper-409]
	at net.minecraft.server.dedicated.DedicatedServer.tickChildren(DedicatedServer.java:490) ~[patched_1.17.1.jar:git-Paper-409]
	at net.minecraft.server.MinecraftServer.tickServer(MinecraftServer.java:1483) ~[patched_1.17.1.jar:git-Paper-409]
	at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1282) ~[patched_1.17.1.jar:git-Paper-409]
	at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:319) ~[patched_1.17.1.jar:git-Paper-409]
	at java.lang.Thread.run(Thread.java:833) ~[?:?]

**Comment by brunyman** [comment]
Should be fixed in version 4.4.0, I will wait for confirmation
