### ISSUE TITLE
Error while stopping server

### ISSUE THREAD

**Issue by Cerexus** [brunyman/MPDB#77]
java.lang.NullPointerException: Cannot invoke "net.minecraft.server.level.WorldServer.v()" because "world" is null
        at net.minecraft.server.level.ServerPlayer.<init>(ServerPlayer.java:261) ~[?:?]
        at net.craftersland.data.bridge.utils.nms.Version_1_18_R2.loadPlayer(Version_1_18_R2.java:135) ~[MysqlPlayerDataBridge-v4.2.0.jar:?]
        at net.craftersland.data.bridge.commands.handlers.SaveAndKickCmd.runCommand(SaveAndKickCmd.java:40) ~[MysqlPlayerDataBridge-v4.2.0.jar:?]
        at net.craftersland.data.bridge.events.ConsoleCommand.onCmd(ConsoleCommand.java:27) ~[MysqlPlayerDataBridge-v4.2.0.jar:?]
        at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor589.execute(Unknown Source) ~[?:?]
        at org.bukkit.plugin.EventExecutor.lambda$create$1(EventExecutor.java:75) ~[paper-api-1.18.2-R0.1-SNAPSHOT.jar:?]
        at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:80) ~[paper-api-1.18.2-R0.1-SNAPSHOT.jar:git-Paper-283]
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[paper-api-1.18.2-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:629) ~[paper-api-1.18.2-R0.1-SNAPSHOT.jar:?]
        at net.minecraft.server.dedicated.DedicatedServer.handleConsoleInputs(DedicatedServer.java:505) ~[paper-1.18.2.jar:git-Paper-283]
        at net.minecraft.server.dedicated.DedicatedServer.tickChildren(DedicatedServer.java:484) ~[paper-1.18.2.jar:git-Paper-283]
        at net.minecraft.server.MinecraftServer.tickServer(MinecraftServer.java:1455) ~[paper-1.18.2.jar:git-Paper-283]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1225) ~[paper-1.18.2.jar:git-Paper-283]
        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:315) ~[paper-1.18.2.jar:git-Paper-283]
        at java.lang.Thread.run(Thread.java:833) ~[?:?]

**Comment by brunyman** [comment]
Fixed in version 4.4.0
