### ISSUE TITLE
async inventory clean error

### ISSUE THREAD

**Issue by MelonHell** [brunyman/MPDB#89]
net.craftersland.data.bridge.events.handlers.InventoryDataHandler
line 246 must be called synchronously

```
java.lang.IllegalStateException: EntityEquipmentEvent may only be triggered synchronously.
   at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:658) ~[paper-api-1.19.2-R0.1-SNAPSHOT.jar:?]
   at me.deecaad.core.events.triggers.EquipListener.lambda$inject$1(EquipListener.java:218) ~[MechanicsCore-1.5.6.jar:?]
   at me.deecaad.core.compatibility.equipevent.NonNullList_1_19_R1.set(NonNullList_1_19_R1.java:55) ~[MechanicsCore-1.5.6.jar:?]
   at me.deecaad.core.compatibility.equipevent.NonNullList_1_19_R1.set(NonNullList_1_19_R1.java:16) ~[MechanicsCore-1.5.6.jar:?]
   at net.minecraft.world.entity.player.Inventory.setItem(Inventory.java:493) ~[?:?]
   at org.bukkit.craftbukkit.v1_19_R1.inventory.CraftInventory.setItem(CraftInventory.java:99) ~[paper-1.19.2.jar:git-Paper-138]
   at org.bukkit.craftbukkit.v1_19_R1.inventory.CraftInventoryPlayer.setItem(CraftInventoryPlayer.java:74) ~[paper-1.19.2.jar:git-Paper-138]
   at org.bukkit.craftbukkit.v1_19_R1.inventory.CraftInventory.clear(CraftInventory.java:442) ~[paper-1.19.2.jar:git-Paper-138]
   at org.bukkit.craftbukkit.v1_19_R1.inventory.CraftInventory.clear(CraftInventory.java:448) ~[paper-1.19.2.jar:git-Paper-138]
   at net.craftersland.data.bridge.events.handlers.InventoryDataHandler.backupAndReset(InventoryDataHandler.java:275) ~[MysqlPlayerDataBridge-v4.6.0.jar:?]
   at net.craftersland.data.bridge.events.handlers.InventoryDataHandler.onJoinFunction(InventoryDataHandler.java:246) ~[MysqlPlayerDataBridge-v4.6.0.jar:?]
   at net.craftersland.data.bridge.utils.Utils.syncCompleteTask(Utils.java:23) ~[MysqlPlayerDataBridge-v4.6.0.jar:?]
   at net.craftersland.data.bridge.events.PlayerJoin$1.run(PlayerJoin.java:32) ~[MysqlPlayerDataBridge-v4.6.0.jar:?]
   at org.bukkit.craftbukkit.v1_19_R1.scheduler.CraftTask.run(CraftTask.java:101) ~[paper-1.19.2.jar:git-Paper-138]
   at org.bukkit.craftbukkit.v1_19_R1.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:57) ~[paper-1.19.2.jar:git-Paper-138]
   at com.destroystokyo.paper.ServerSchedulerReportingWrapper.run(ServerSchedulerReportingWrapper.java:22) ~[paper-1.19.2.jar:?]
   at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136) ~[?:?]
   at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635) ~[?:?]
   at java.lang.Thread.run(Thread.java:833) ~[?:?]
```

**Comment by brunyman** [comment]
**Fixed in last update, please confirm.**

**Comment by brunyman** [comment]
Fixed in latest version
