### ISSUE TITLE
IMPORTANT・Duplication money CMI

### ISSUE THREAD

**Issue by NebulusFR** [brunyman/MPDB#94]
My player leave and join another server, sometimes, money is multipliate

https://pastebin.com/pkE415GZ

**Comment by NebulusFR** [comment]
![image](https://user-images.githubusercontent.com/36241286/210122005-8574cefc-0664-4f10-9306-61017fa7128c.png)

**Comment by kpAjun** [comment]
#96 Experiencing inventory issues with MPDB too, restart is surely bugged.

**Comment by NebulusFR** [comment]
I don't have a problem with inventory, only money since I've been using this plugin (a few months)
I'm using this version of Arclight under JAVA 11: https://github.com/IzzelAliz/Arclight/releases/tag/1.16%2F1.0.24
My economy is managed by CMI with their customized version of Vault
Money is withdrawn or added to certain logouts and logins. I'm a network with 10 servers, players are constantly browsing the different servers
I often have an error in my console coming from the plugin but I don't know this is related

```
[04Jan2023 12:45:47.332] [Craft Scheduler Thread - 217/WARN] [MysqlPlayerDataBridge/]: Plugin MysqlPlayerDataBridge v4.6.0 generated an exception while executing task 100
java.util.ConcurrentModificationException: null
	at java.util.ArrayList$Itr.checkForComodification(ArrayList.java:1043) ~[?:?]
	at java.util.ArrayList$Itr.next(ArrayList.java:997) ~[?:?]
	at com.google.common.collect.TransformedIterator.next(TransformedIterator.java:47) ~[arclight-forge-1.16.5-1.0.25-SNAPSHOT.jar:arclight-1.16.5-1.0.25-SNAPSHOT-eea2c2bb]
	at java.util.Collections$UnmodifiableCollection$1.next(Collections.java:1047) ~[?:?]
	at net.craftersland.data.bridge.runnables.LiveOfflineBalanceUpdateTask.run(LiveOfflineBalanceUpdateTask.java:22) ~[MysqlPlayerDataBridge-v4.6.0.jar:?]
	at org.bukkit.craftbukkit.v1_16_R3.scheduler.CraftTask.run(CraftTask.java:81) ~[arclight:arclight-1.16.5-1.0.25-SNAPSHOT-eea2c2bb]
	at org.bukkit.craftbukkit.v1_16_R3.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:54) [arclight:arclight-1.16.5-1.0.25-SNAPSHOT-eea2c2bb]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128) [?:?]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628) [?:?]
	at java.lang.Thread.run(Thread.java:829) [?:?]
```

**Comment by NebulusFR** [comment]
@brunyman

**Comment by NebulusFR** [comment]
It's starting to feel urgent. The bug has been present for a few months (since my server is open in its new version). We are partners with Discord.com, Instant-Gaming.com and Minecraft.fr. We are going to start a big additional communication phase but we cannot as long as this problem persists because it happens very often and spoils the game experience. Players win or lose money very often. This wastes time for the administration, which has nothing to do with coming to reimburse and remove money from several tens or even hundreds of players

**Comment by NebulusFR** [comment]
UP @brunyman
